services:
  player1:
    build: .
    network_mode: bridge
    container_name: game_player1
    
  player2:
    build: .
    network_mode: bridge
    container_name: game_player2
    
  player3:
    build: .
    network_mode: bridge
    container_name: game_player3
